### ISSUE TITLE
Autonomous registration of users

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/authentication-server#10]
@mmalfertheiner 
I describe the customer journey here for a better understanding. Just pick the tasks that are yours...

**Moderators:**
A user logs into virtual.noi.bz.it, or if the user does not have an account, it can register with name, surname, and email. The email gets verified with the common workflow, that the new user gets a email and has to click on some links there to enable that email. The user  will then be redirected and logged in into virtual.noi.bz.it. He must have the rights to generate, modify and delete his events (this is done through the Tourism API, where the token from keycloak contains the corresponding role).

**Admins:**
In addition, the virtual.noi.bz.it admins (people from NOI) get a notification email, that a new user has registered. 
These admins are a group of people, we do not want to get all registration notification from all projects. For example, if registred through san virtual, some people get a notification, and if registered through another web app, other admins get notified.

**Account activation:**
The account must be activated without further actions from admins, but admins can later revoke permissions or completely delete accounts. For that, we just use the standard keycloak interface. Maybe just giving some instructions on how to use it, for non-techies :-)

**Themes:**
For now we just extend the NOI theme, but later we would like to have also a virtual.noi.bz.it theme (nice-to-have), or other themes (future-plans).

**Realms:**
Single realm (NOI), advantage single account for TTDigital admins. Newly registered users are connected to the REALM and not only to the application. We could give those users a default roles, so if for example a user registeres on analytics, he can also access to virtual.noi.bz.it.... (similar to Google, where you have an account for Gmail which is then also active for Gdocs, etc.)... All services from us, that allow auto-signup, are already present inside the default role. For special services, like analytics.opendatahub.bz.it, an admin from TTDigital must grant access permissions. We implement this with a GUEST group, which contains all default roles/permissions.

**Non-goals**
For now, we do not ask the user to grant permissions to certain services, for example: "Do you want to give application XY access to your account data?"

**DEADLINE**
End of November, 25th (to have some time to test)

**Comment by Piiit** [comment]
@ohnewein @sseppi FYI

**Comment by mmalfertheiner** [comment]
- [ ] Extend NOI Theme with Registration flow
- [ ] Assign newly registered user to guest group
- [ ] Notify NOI admins when new user registers
- [ ] Create a custom Sankt Virtual theme

**Comment by ohnewein** [comment]
@RudiThoeni accepts pull-request and writes an e-mail to Davide Montesin and Martin Malfertheiner, with Patrick O and Stefano in CC, to coordinate works.

**Comment by RudiThoeni** [comment]
email written, Martin has completed work on Registration form, on Keycloak Test Group + Role + Registration Settings activated, tested, should work

**Comment by Piiit** [comment]
@mmalfertheiner 

Finalization TODOs

- [ ] Backlink to referrer / Near the LOGO: New text of the referrer which is the "name" attribute in keycloak and linkback to the baseurl in keycloak (no 500, if something is wrong or missing)
- [ ] Registration link more prominent
