### ISSUE TITLE
EPIC: Authentication Server integration

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/authentication-server#22]
Create a roadmap for integrations to keycloak and projects that will not be integrated

File: https://docs.google.com/spreadsheets/d/1382YxR1KakHSNMJNwmX7XZZGrrKQU6H-m2qNM8kdmtY

**Comment by Piiit** [comment]
@ohnewein FYI

**Comment by rcavaliere** [comment]
Currently focus is on NexCloud

**Comment by RudiThoeni** [comment]
sseppi will contact qbus

**Comment by RudiThoeni** [comment]
todo for all, test nextcloud authentication server integration

**Comment by RudiThoeni** [comment]
I tested and all files were transferred successfully on nextcloud
