### ISSUE TITLE
Integrate Microsoft Accounts into Keycloak

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/authentication-server#56]
- [x] @mmalfertheiner adds a microsoft login to the template
- [x] Berni and @mmalfertheiner configure Keycloak and Azure
- [x] @mmalfertheiner writes documentation about the Keycloak config
- [x] Berni activates test user, @Piiit tests
- [x] Berni activates all NOI users (login is disabled until then)
- [x] Activation email lands in quarantine, that is a problem since it is only valid for 15 minutes, Berni and @Piiit look for a solution
> Berni wrote to Microsoft, we had this problem already in the past, the solution took about 1 week in the past... so we cannot do anything at the moment

**Comment by Piiit** [comment]
Blocked until Berni comes back --> 22/11/2021

**Comment by Piiit** [comment]
@sseppi FYI
