### ISSUE TITLE
Change the NOI Login Template

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/authentication-server#57]
- Title (near the upper left NOI logo) = Open Data Hub Login
- Microsoft Login -> NOI Techpark (maybe not repeating the NOI logo, otherwise it would be double on the page)

**Comment by mmalfertheiner** [comment]
> Title (near the upper left NOI logo) = Open Data Hub Login

Replace the current title with this?

> Microsoft Login -> NOI Techpark (maybe not repeating the NOI logo, otherwise it would be double on the page)

without the Microsoft icon?

**Comment by Piiit** [comment]
Works, thank you @mmalfertheiner
