### ISSUE TITLE
As a Yanovis user I want to use my company username and password to access the Open Data Hub in order to avoid the creation of new credentials.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/authentication-server#61]
Medium Priority, Deadline 15 March 2022

**Comment by RudiThoeni** [comment]
@sseppi  the integration of yannovis to keycloak is done, can we close this issue?

**Comment by mmalfertheiner** [comment]
@RudiThoeni there is one open question here: https://github.com/noi-techpark/authentication-server/issues/68

**Comment by sseppi** [comment]
@mmalfertheiner I've provided the feedback in the other issue
