### ISSUE TITLE
Complete GithubActions CI

### ISSUE THREAD

**Issue by dulvui** [noi-techpark/authentication-server#64]
Complete the GithubActions CI started by @dulvui

**Comment by alexlanz** [comment]
What exactly is here to do?

**Comment by dulvui** [comment]
I tried to create the CI for this repo but got a `permission denied, access '/code/themes/noiV2/common/resources`.
Could you please try to fix this problem so that the CI runs correctly?

**Comment by alexlanz** [comment]
Ok, I will take a look at it after I completed the other tasks in the Kanban board that are higher ranked.
