### ISSUE TITLE
As an opendatahub developer i want to have auth.opendatahub.com as primary authenticationserver url used on all services

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/authentication-server#86]
Checklist
- [x] Mobility Api
- [x] Tourism Api
- [x] Mobility Writer
- [x] Tourism Importer
- [x] Datacollectors Mobility
- [x] Mobility R Library
- [x] Alpinebits Server Tourism
- [x] Issue Tracker
- [x] Nextcloud
- [x] Mentor
- [x] Grafana
- [x] Webcomp Push Action
- [x] Webcomponent Store
- [x] Check Various Api Calls for 401 (Minsait, Zeppelin etc...)
- [x] Hello World Datacollector
- [x] Webcomponent mobility Traffic
- [x] Epaper
- [x] Innovation Scoreboard Davinci
- [x] ODH Tourism Cron
- [x] Community Api
- [x] NOI Community App
- [x] Calendar Api
- [x] Databrowser
- [x] Sankt Virtual (needed?)

**Comment by ohnewein** [comment]
Thank you Rudi for the excellent work to get the domain issue cleaned up!

**Comment by RudiThoeni** [comment]
> Thank you Rudi for the excellent work to get the domain issue cleaned up!

thank you, many Thanks also to Simon for the good teamwork ;)

**Comment by RudiThoeni** [comment]
closing this issue, all exposed services are available with the new domain, continuing in https://github.com/noi-techpark/authentication-server/issues/90 for internal services migration
